---

- name: Deploy initial AAP config (org, users, teams, etc.)
  hosts: localhost
  gather_facts: false
  vars:
    aap_validate_certs: false
    local_clone_path: "/tmp/{{ awx_webhook_payload.repository.name }}"
    source_repo_url: "{{ awx_webhook_payload.repository.clone_url }}"
  pre_tasks:
    - name: Launch a Project with extra_vars without waiting
      ansible.controller.project_update:
        project: "{{ awx_webhook_payload.repository.name }}"
        wait: true

    - name: Wait for 10 seconds to ensure project is ready
      ansible.builtin.pause:
        seconds: 10

    - name: Ensure local_clone_path does not exist before cloning
      ansible.builtin.file:
        path: "{{ local_clone_path }}"
        state: absent

    - name: Clone the source repository
      ansible.builtin.git:
        repo: "{{ source_repo_url }}"
        dest: "{{ local_clone_path }}"

    - name: Debug local_clone_path
      ansible.builtin.debug:
        msg: "Cloned repository to {{ local_clone_path }}"

    - name: Include vars from directory
      ansible.builtin.include_vars:
        dir: "{{ local_clone_path }}/ansible/vars"
        extensions: ["yml"]
      tags:
        - always
  roles:
    - infra.aap_configuration.dispatch
