---

- name: Run ansible-lint on playbooks
  hosts: localhost
  gather_facts: false
  vars:
    local_clone_path: "/tmp/{{ awx_webhook_payload.repository.name }}"
    source_repo_url: "{{ awx_webhook_payload.repository.clone_url }}"
  vars_files:
    - vars/main.yml
  tasks:
    - name: Clone Git repository with playbooks
      ansible.builtin.git:
        repo: "{{ source_repo_url }}"
        dest: "{{ local_clone_path }}"
        force: true
      register: git_clone

    - name: Find all Ansible playbooks
      ansible.builtin.find:
        paths: "{{ local_clone_path }}/playbooks"
        patterns: "*.yml"
        recurse: true
      register: ls_output

    - name: Execute ansible-lint
      ansible.builtin.command:
        cmd: ansible-lint -p -q {{ local_clone_path }}/playbooks/{{ item }}
      ignore_errors: true
      check_mode: false
      changed_when: true
      loop: "{{ ls_output.stdout_lines }}"
      register: lint_result

    - name: Display ansible-lint results
      ansible.builtin.debug:
        var: item.stderr_lines
      loop: "{{ lint_result.results }}"

    - name: Fail if ansible-lint found issues
      ansible.builtin.fail:
        msg: "ansible-lint found issues in the playbooks."
      when: lint_result.results | selectattr('failed', 'equalto', true) | list | length > 0
      ignore_errors: true

    - name: Send error to Slack if linting fails
      community.general.slack:
        token: "{{ slack_token }}"
        msg: |
          :warning: ansible-lint found issues in the playbooks of repository {{ awx_webhook_payload.repository.name }}. :warning:
          Please review the linting results and address the issues.
        channel: "{{ slack_channel }}"
        username: "AnsibleLintBot"
        icon_emoji: ":warning:"
      when: lint_result.results | selectattr('failed', 'equalto', true) | list | length > 0
      failed_when: true
